# Generated by Django 6.0.2 on 2026-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='about_company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
