# Generated by Django 6.0.2 on 2026-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience_about_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='about_company',
            field=models.URLField(blank=True),
        ),
    ]
