# Generated by Django 6.0.2 on 2026-04-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_experience_about_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='from_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
